#%RAML 1.0
title: sampleraml
description: this is sample raml project

/helloworld:
  get: 
    responses: 
      200:
        body: 
          application/json: 
            type: |
              {
                "title": "Hello world Response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                }
              }
            example: | 
              {
                "message": "Hello world"
              }

            
    